[package]
name = "fhe_precompiles"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["staticlib", "rlib"]

[dependencies]
crypto-bigint = "0.4.9"
bincode = "1.3.3"
libc = "0.2.139"
once_cell = "1.17.1"
paste = "1.0.12"
sunscreen = { git = "https://github.com/Sunscreen-tech/Sunscreen", rev = "26bd6dab37e0a5fec13f325a2be40da988062ad0" }

[dev-dependencies]
serde = "1.0.160"
